FROM maven:3.6.0-jdk-11-slim AS MAVEN_BUILD

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn package

FROM openjdk:11.0.1-jdk-slim

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/io.connectedhealth_idaas.kic-05-01.jar /app/

ENTRYPOINT ["java", "-jar", "io.connectedhealth_idaas.kic-05-01.jar"]