name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "main"
      increment-major:
        description: "Should we increment the major version (true/false)"
        required: true
        default: "false"
      increment-minor:
        description: "Should we increment the minor version (true/false)"
        required: true
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
    - name: Java Maven release Upstream
      uses: qcastel/github-actions-maven-release@v1.12.16
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        MAVEN_REPO_SERVER_ID: github
        MAVEN_REPO_SERVER_USERNAME: idaas-bot
        MAVEN_REPO_SERVER_PASSWORD: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
      with:
        access-token: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
        release-branch-name: ${{ github.event.inputs.branch }}
        version-major: ${{ github.event.inputs.increment-major }}
        version-minor: ${{ github.event.inputs.increment-minor }}
        git-release-bot-name: "idaas-bot"
        maven-options: "-s /github/workspace/.github/workflows/settings.xml"
        maven-args: "-Dmaven.deploy.skip=true"
        maven-repo-server-id: github
    - name: Deploy Red Hat Artifacts
      run: mvn -s /github/workspace/.github/workflows/settings.xml -B deploy --file pom.xml
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        MAVEN_REPO_SERVER_ID: github
        MAVEN_REPO_SERVER_USERNAME: idaas-bot
        MAVEN_REPO_SERVER_PASSWORD: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
